# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EstateAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('region', models.IntegerField(choices=[(1, 'Ljubljana - okolica'), (2, 'Južna primorska'), (3, 'Gorenjska'), (4, 'Severna primorska'), (5, 'Savinjska'), (6, 'Dolenjska'), (8, 'Notranjska'), (9, 'Podravska'), (10, 'Koroška'), (11, 'Zasavska'), (12, 'Posavska'), (14, 'Ljubljana - mesto'), (15, 'Pomurska')], db_index=True)),
                ('type', models.IntegerField(choices=[(0, 'Prodaja'), (1, 'Nakup'), (2, 'Oddaja'), (3, 'Najem')], db_index=True, null=True)),
                ('building_type', models.IntegerField(choices=[(0, 'Stanovanje'), (1, 'Hiša'), (2, 'Posest'), (3, 'Poslovni prostor'), (4, 'Garaža'), (5, 'Vikend')], db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('short_description', models.TextField(blank=True, default='')),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('publish_date', models.DateTimeField()),
                ('size_m2', models.FloatField(null=True)),
                ('price_m2', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('year_built', models.IntegerField(null=True)),
                ('floor', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('administrative_unit', models.CharField(blank=True, default='', max_length=255)),
                ('county', models.CharField(blank=True, default='', max_length=255)),
                ('raw_data', models.TextField()),
                ('raw_html', models.TextField()),
                ('raw_detail_html', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='adpicture',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estate_ads.EstateAd'),
        ),
    ]
